export const FETCH_REPOSITORY = 'FETCH_REPOSITORY';
export const FETCH_SINGLE_REPOSITORY = 'FETCH_SINGLE_REPOSITORY';
export const LOADING_REPOSITORY = 'LOADING_REPOSITORY';
export const LOADING_FOLDER = 'LOADING_FOLDER';
export const FETCH_FOLDER = 'FETCH_FOLDER';
export const FETCH_FOLDER_FROM_DOCUMENT = 'FETCH_FOLDER_FROM_DOCUMENT';
